import type { Metadata } from "next";
import "./globals.css";

import { McLaren } from "next/font/google";

const mclaren = McLaren({
  weight: "400", 
  subsets: ["latin"], 
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mclaren.className} ${mclaren.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
